### PR TITLE
Port `.travis.yml` to Github Actions

### LINKED ISSUE #21: Move from Travis CI to Github Actions for CI
Since June earlier this year, Travis CI no longer supports free open source CI. 

Github Actions has become the defacto standard for CI for open source projects. [This repository](https://github.com/jefftriplett/python-github-actions-matrix-demo) offers a good template to use to port the existing `.travis.yml` over.

### PR DESCRIPTION
**Pull request by joshuadavidthomas**
This PR closes #21.

### CODE REVIEW

**Review by pauloxnet — APPROVED** [review]

**Comment by pauloxnet** [comment]
@nickpresta can you merge this PR so we can move on with other PRs with Python/Django updates?

**Comment by nickpresta** [comment]
Hi @pauloxnet 👋 

I don't work at Wave anymore. Perhaps @nduthoit or @dangreenisrael could help  out (also, hi friends!)

**Comment by pauloxnet** [comment]
> Hi @pauloxnet wave
> 
> I don't work at Wave anymore. Perhaps @nduthoit or @dangreenisrael could help out (also, hi friends!)

@nickpresta thanks for your answer! So we'll wait an answer from your former colleagues.

**Comment by joshuadavidthomas** [comment]
This PR probably needs to be updated since new versions of Django have been released since I first opened it.

**Pull request closed without merging**
